ALTER TABLE "booking_details" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "booking" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "movies" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "movies" ALTER COLUMN "release_date" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "screens" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "seats" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "seats" ALTER COLUMN "screen_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "shows" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET GENERATED BY DEFAULT;